version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: magrathea-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magrathea
      - MYSQL_DATABASE=magrathea
      - MYSQL_USER=magrathea
      - MYSQL_PASSWORD=magrathea
    ports:
      - "8002:3306"
